strategy: null # 'ddp' for multi gpu 
benchmark: True
max_epochs: 1501
accelerator: gpu
log_every_n_steps: 40 # 100
deterministic: False
detect_anomaly: False
enable_progress_bar: True
check_val_every_n_epoch: 200 # if k --> happens every (k-1), 2*(k-1), ...
limit_train_batches: 1.0
limit_val_batches: 1.0
num_sanity_val_steps: 0 # 2
precision: 32 # => 'bf16' | 16 | 32
