_target_: diffusers.DDIMScheduler
num_train_timesteps: 1000
beta_start: 0.00085
beta_end: 0.012
beta_schedule: 'scaled_linear' # Optional: ['linear', 'scaled_linear', 'squaredcos_cap_v2']
# variance_type: 'fixed_small'
clip_sample: false # clip sample to -1~1
prediction_type: sample
# below are for ddim
set_alpha_to_one: false
steps_offset: 1